#!/bin/sh
./../qt-everywhere-opensource-src-5.9.2/configure \
-verbose \
-opensource \
-release \
-shared \
-confirm-license \
-linuxfb \
-make libs \
-nomake tools \
-nomake examples \
-nomake tests \
-no-feature-cursor \
-no-qml-debug \
-no-use-gold-linker \
-no-iconv \
-no-opengl \
-xplatform linux-arm-gnueabi-g++ \
-prefix /opt/qt-5.9.2-imx6-noopengl \
-I/opt/fsl-image-gui-imx6qsabresd/usr/include \
-L/opt/fsl-image-gui-imx6qsabresd/usr/lib \
-I/opt/tslib-1.11/include \
-L/opt/tslib-1.11/lib